# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ansi` gem.
# Please instead update this file by running `bin/tapioca gem ansi`.


# ANSI namespace module contains all the ANSI related classes.
#
# pkg:gem/ansi#lib/ansi.rb:2
module ANSI
  extend ::ANSI::Constants
  extend ::ANSI::Code

  class << self
    # Create a new Ansi::String object.
    #
    # pkg:gem/ansi#lib/ansi/string.rb:5
    def string(str); end
  end
end

# The BBCode module helps ease the separation of core and frontend with the
# core (or submodules) being still able to say, what colors shall be used
# in it's responses. This is achieved by encoding formatting information
# using the BBCode tokens. This enables you to "pipe" layout information
# such as colors, style, font, size and alignment through the core to
# the frontend.
#
# Additionally it converts markups/codes between ANSI, HTML and BBCode
# almost freely ;)
#
#   # Converting a bbcode string to ANSI and XHTML
#   str = "this is [COLOR=red]red[/COLOR], this is [B]bold[/B]"
#   print( BBCode.bbcode_to_ansi(str) )
#   print( BBCode.bbcode_to_html(str) )
#
# pkg:gem/ansi#lib/ansi/bbcode.rb:32
module ANSI::BBCode
  class << self
    # Returns the ANSI sequence for given color, if existant
    #
    # pkg:gem/ansi#lib/ansi/bbcode.rb:88
    def ansi(colorname); end

    # Returns the string with all ansi escape sequences converted to BBCodes
    #
    # pkg:gem/ansi#lib/ansi/bbcode.rb:101
    def ansi_to_bbcode(string); end

    # Converts an ANSI string to one with HTML markup.
    # Returns the string with ANSI code sequences converted to XHTML markup.
    #
    # pkg:gem/ansi#lib/ansi/bbcode.rb:316
    def ansi_to_html(string); end

    # Converts a BBCode string to one with ANSI sequences.
    # Returns the string with all formatting instructions in BBCodes converted
    # to ANSI code sequences / aligned with spaces to specified width.
    #
    # pkg:gem/ansi#lib/ansi/bbcode.rb:144
    def bbcode_to_ansi(string, usecolors = T.unsafe(nil)); end

    # Converts a BBCode string to one with HTML markup.
    # Returns the string with all formatting instructions in
    # BBCodes converted to XHTML markups.
    #
    # pkg:gem/ansi#lib/ansi/bbcode.rb:251
    def bbcode_to_html(string); end

    # Returns the (X)HTML markup code as ANSI sequences
    #
    # pkg:gem/ansi#lib/ansi/bbcode.rb:324
    def html_to_ansi(string); end

    # Converts a HTML string into one with BBCode markup (TODO)
    # Returns the (X)HTML markup string as BBCode
    #
    # pkg:gem/ansi#lib/ansi/bbcode.rb:192
    def html_to_bbcode(string); end

    # --- strip_bbcode( string )
    # Will strip any BBCode tags from the given string.
    #
    # pkg:gem/ansi#lib/ansi/bbcode.rb:95
    def strip_bbcode(string); end
  end
end

# ANSInames => BBCode LUT
#
# pkg:gem/ansi#lib/ansi/bbcode.rb:72
ANSI::BBCode::ANSINAME2BBCODE = T.let(T.unsafe(nil), Hash)

# ANSIname => ANSIcode LUT
#
# pkg:gem/ansi#lib/ansi/bbcode.rb:35
ANSI::BBCode::ANSINAME2CODE = T.let(T.unsafe(nil), Hash)

# BBColor => ANSIname LUT
#
# pkg:gem/ansi#lib/ansi/bbcode.rb:53
ANSI::BBCode::BBCOLOR2ANSI = T.let(T.unsafe(nil), Hash)

# Table of codes used throughout the system.
#
# @see http://en.wikipedia.org/wiki/ANSI_escape_code
#
# pkg:gem/ansi#lib/ansi/chart.rb:6
ANSI::CHART = T.let(T.unsafe(nil), Hash)

# ANSI::Chain was inspired by Kazuyoshi Tlacaelel's Isna library.
#
# pkg:gem/ansi#lib/ansi/chain.rb:7
class ANSI::Chain
  # pkg:gem/ansi#lib/ansi/chain.rb:10
  def initialize(string); end

  # pkg:gem/ansi#lib/ansi/chain.rb:19
  def codes; end

  # pkg:gem/ansi#lib/ansi/chain.rb:22
  def method_missing(s, *a, &b); end

  # pkg:gem/ansi#lib/ansi/chain.rb:16
  def string; end

  # pkg:gem/ansi#lib/ansi/chain.rb:32
  def to_s; end

  # pkg:gem/ansi#lib/ansi/chain.rb:43
  def to_str; end
end

# ANSI Codes
#
# Ansi::Code module makes it very easy to use ANSI codes.
# These are especially nice for beautifying shell output.
#
#   Ansi::Code.red + "Hello" + Ansi::Code.blue + "World"
#   => "\e[31mHello\e[34mWorld"
#
#   Ansi::Code.red{ "Hello" } + Ansi::Code.blue{ "World" }
#   => "\e[31mHello\e[0m\e[34mWorld\e[0m"
#
# IMPORTANT! Do not mixin Ansi::Code, instead use {ANSI::Mixin}.
#
# See {ANSI::CHART} for list of all supported codes.
#
# pkg:gem/ansi#lib/ansi/code.rb:37
module ANSI::Code
  include ::ANSI::Constants
  extend ::ANSI::Constants
  extend ::ANSI::Code

  # Return ANSI code given a list of symbolic names.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:60
  def [](*codes); end

  # Apply ANSI codes to a first argument or block value.
  #
  # @example
  #   ansi("Valentine", :red, :on_white)
  #
  # @example
  #   ansi(:red, :on_white){ "Valentine" }
  #
  # @return [String]
  #   String wrapped ANSI code.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:176
  def ansi(*codes); end

  # pkg:gem/ansi#lib/ansi/code.rb:152
  def back(spaces = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def black_on_black(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def black_on_blue(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def black_on_cyan(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def black_on_green(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def black_on_magenta(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def black_on_red(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def black_on_white(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def black_on_yellow(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def blue_on_black(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def blue_on_blue(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def blue_on_cyan(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def blue_on_green(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def blue_on_magenta(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def blue_on_red(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def blue_on_white(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def blue_on_yellow(string = T.unsafe(nil)); end

  # Look-up code from chart, or if Integer simply pass through.
  # Also resolves :random and :on_random.
  #
  # @param codes [Array<Symbol,Integer]
  #   Symbols or integers to convert to ANSI code.
  #
  # @return [String] ANSI code
  #
  # pkg:gem/ansi#lib/ansi/code.rb:241
  def code(*codes); end

  # Alternate term for #ansi.
  #
  # @deprecated
  #   May change in future definition.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:226
  def color(*codes); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def cyan_on_black(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def cyan_on_blue(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def cyan_on_cyan(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def cyan_on_green(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def cyan_on_magenta(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def cyan_on_red(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def cyan_on_white(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def cyan_on_yellow(string = T.unsafe(nil)); end

  # Like +move+ but returns to original position after
  # yielding the block.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:120
  def display(line, column = T.unsafe(nil)); end

  # Move cursor down a specified number of spaces.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:144
  def down(spaces = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:158
  def forward(spaces = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def green_on_black(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def green_on_blue(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def green_on_cyan(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def green_on_green(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def green_on_magenta(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def green_on_red(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def green_on_white(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def green_on_yellow(string = T.unsafe(nil)); end

  # Creates an xterm-256 color code from a CSS-style color string.
  #
  # @param string [String]
  #   Hex string in CSS style, .e.g. `#5FA0C2`.
  #
  # @param background [Boolean]
  #   Use `true` for background color, otherwise foreground color.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:325
  def hex_code(string, background = T.unsafe(nil)); end

  # Move cursor left a specified number of spaces.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:149
  def left(spaces = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def magenta_on_black(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def magenta_on_blue(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def magenta_on_cyan(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def magenta_on_green(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def magenta_on_magenta(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def magenta_on_red(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def magenta_on_white(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def magenta_on_yellow(string = T.unsafe(nil)); end

  # Use method missing to dispatch ANSI code methods.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:89
  def method_missing(code, *args, &blk); end

  # Move cursor to line and column.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:134
  def move(line, column = T.unsafe(nil)); end

  # Provides a random primary ANSI color.
  #
  # @param background [Boolean]
  #   Use `true` for background color, otherwise foreground color.
  #
  # @return [Integer] ANSI color number
  #
  # pkg:gem/ansi#lib/ansi/code.rb:274
  def random(background = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def red_on_black(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def red_on_blue(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def red_on_cyan(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def red_on_green(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def red_on_magenta(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def red_on_red(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def red_on_white(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def red_on_yellow(string = T.unsafe(nil)); end

  # Creates an XTerm 256 color escape code from RGB value(s). The
  # RGB value can be three arguments red, green and blue respectively
  # each from 0 to 255, or the RGB value can be a single CSS-style
  # hex string.
  #
  # @param background [Boolean]
  #   Use `true` for background color, otherwise foreground color.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:286
  def rgb(*args); end

  # Given red, green and blue values between 0 and 255, this method
  # returns the closest XTerm 256 color value.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:335
  def rgb_256(r, g, b); end

  # Creates an xterm-256 color from rgb value.
  #
  # @param background [Boolean]
  #   Use `true` for background color, otherwise foreground color.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:313
  def rgb_code(red, green, blue, background = T.unsafe(nil)); end

  # Move cursor right a specified number of spaces.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:155
  def right(spaces = T.unsafe(nil)); end

  # Alias for #ansi method.
  #
  # @deprecated
  #   Here for backward compatibility.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:214
  def style(*codes); end

  # Remove ANSI codes from string or block value.
  #
  # @param [String] string
  #   String from which to remove ANSI codes.
  #
  # @return [String]
  #   String wrapped ANSI code.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:201
  def unansi(string = T.unsafe(nil)); end

  # Alias for unansi.
  #
  # @deprecated
  #   May change in future definition.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:232
  def uncolor(string = T.unsafe(nil)); end

  # Alias for #unansi method.
  #
  # @deprecated
  #   Here for backwards compatibility.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:220
  def unstyle(string = T.unsafe(nil)); end

  # Move cursor up a specified number of spaces.
  #
  # pkg:gem/ansi#lib/ansi/code.rb:139
  def up(spaces = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def white_on_black(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def white_on_blue(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def white_on_cyan(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def white_on_green(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def white_on_magenta(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def white_on_red(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def white_on_white(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def white_on_yellow(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def yellow_on_black(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def yellow_on_blue(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def yellow_on_cyan(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def yellow_on_green(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def yellow_on_magenta(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def yellow_on_red(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def yellow_on_white(string = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/code.rb:70
  def yellow_on_yellow(string = T.unsafe(nil)); end

  class << self
    # List of primary colors.
    #
    # pkg:gem/ansi#lib/ansi/code.rb:55
    def colors; end

    # List of primary styles.
    #
    # pkg:gem/ansi#lib/ansi/code.rb:50
    def styles; end
  end
end

# ANSI clear code.
#
# pkg:gem/ansi#lib/ansi/code.rb:47
ANSI::Code::ENDCODE = T.let(T.unsafe(nil), String)

# Regexp for matching most ANSI codes.
#
# pkg:gem/ansi#lib/ansi/code.rb:44
ANSI::Code::PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/ansi#lib/ansi/columns.rb:6
class ANSI::Columns
  # Create a column-based layout.
  #
  # @param [String,Array] list
  #   Multiline String or Array of strings to columnize.
  #
  # @param [Hash] options
  #   Options to customize columnization.
  #
  # @option options [Fixnum] :columns
  #   Number of columns.
  #
  # @option options [Symbol] :align
  #   Column alignment, either :left, :right or :center.
  #
  # @option options [String,Fixnum] :padding
  #   String or number or spaces to append to each column.
  #
  # The +format+ block MUST return ANSI codes.
  #
  # pkg:gem/ansi#lib/ansi/columns.rb:26
  def initialize(list, options = T.unsafe(nil), &format); end

  # Alignment to apply to cells.
  #
  # pkg:gem/ansi#lib/ansi/columns.rb:82
  def align; end

  # Set alignment ensuring value is a symbol.
  #
  # @param [#to_sym] symbol
  #   Either `:right`, `:left` or `:center`.
  #
  # @return [Symbol] The given symbol.
  #
  # pkg:gem/ansi#lib/ansi/columns.rb:90
  def align=(symbol); end

  # Default number of columns to display. If nil then the number
  # of coumns is estimated from the size of the terminal.
  #
  # pkg:gem/ansi#lib/ansi/columns.rb:58
  def columns; end

  # Set column count ensuring value is either an integer or nil.
  # The the value given is zero, it will be taken to mean the same
  # as nil, which means fit-to-screen.
  #
  # pkg:gem/ansi#lib/ansi/columns.rb:63
  def columns=(integer); end

  # Formating to apply to cells.
  #
  # pkg:gem/ansi#lib/ansi/columns.rb:98
  def format; end

  # Set formatting procedure. The procedure must return
  # ANSI codes, suitable for passing to String#ansi method.
  #
  # pkg:gem/ansi#lib/ansi/columns.rb:102
  def format=(procedure); end

  # pkg:gem/ansi#lib/ansi/columns.rb:39
  def inspect; end

  # pkg:gem/ansi#lib/ansi/columns.rb:116
  def join(cols = T.unsafe(nil)); end

  # List layout into columns. Each new line is taken to be
  # a row-column cell.
  #
  # pkg:gem/ansi#lib/ansi/columns.rb:45
  def list; end

  # pkg:gem/ansi#lib/ansi/columns.rb:47
  def list=(list); end

  # Padding size to apply to cells.
  #
  # pkg:gem/ansi#lib/ansi/columns.rb:69
  def padding; end

  # Set padding to string or number (of spaces).
  #
  # pkg:gem/ansi#lib/ansi/columns.rb:72
  def padding=(pad); end

  # Return string in column layout. The number of columns is determined
  # by the `columns` property or overriden by +cols+ argument.
  #
  # pkg:gem/ansi#lib/ansi/columns.rb:111
  def to_s(cols = T.unsafe(nil)); end

  private

  # Used to apply ANSI formatting to each cell.
  #
  # pkg:gem/ansi#lib/ansi/columns.rb:177
  def ansi_formatting(cell, col, row); end

  # Aligns the cell left or right.
  #
  # pkg:gem/ansi#lib/ansi/columns.rb:164
  def template(max, pad); end

  # Layout string lines into columns.
  #
  # @todo Put in empty strings for blank cells.
  # @todo Centering look like it's off by one to the right.
  #
  # pkg:gem/ansi#lib/ansi/columns.rb:127
  def to_s_columns(columns = T.unsafe(nil)); end
end

# Converts {CHART} and {SPECIAL_CHART} entries into constants.
# So for example, the CHART entry for :red becomes:
#
#   ANSI::Constants::RED  #=> "\e[31m"
#
# The ANSI Constants are include into ANSI::Code and can be included
# any where will they would be of use.
#
# pkg:gem/ansi#lib/ansi/constants.rb:13
module ANSI::Constants; end

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::BLACK = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::BLINK = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::BLINK_OFF = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::BLUE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::BOLD = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::BOLD_OFF = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::BRIGHT = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::BRIGHT_OFF = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::CLEAN = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::CLEAR = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:20
ANSI::Constants::CLEAR_EOL = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:20
ANSI::Constants::CLEAR_LEFT = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:20
ANSI::Constants::CLEAR_LINE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:20
ANSI::Constants::CLEAR_RIGHT = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:20
ANSI::Constants::CLEAR_SCREEN = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:20
ANSI::Constants::CLR = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:20
ANSI::Constants::CLS = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::CONCEAL = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::CONCEALED = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::CONCEAL_OFF = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::CROSSED_OFF = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::CROSSED_OUT_OFF = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:20
ANSI::Constants::CURSOR_HIDE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:20
ANSI::Constants::CURSOR_SHOW = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::CYAN = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::DARK = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::DEFAULT_FONT = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::DOUBLE_UNDERLINE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::ENCIRCLE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::ENCIRCLE_OFF = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FAINT = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FONT0 = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FONT1 = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FONT2 = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FONT3 = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FONT4 = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FONT5 = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FONT6 = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FONT7 = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FONT8 = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FONT9 = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FONT_DEFAULT = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FRAKTUR = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FRAKTUR_OFF = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FRAME = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::FRAME_OFF = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::GREEN = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::HIDE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::INVERSE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::INVERSE_OFF = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::INVERT = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::ITALIC = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::ITALIC_OFF = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::MAGENTA = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::NEGATIVE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::ON_BLACK = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::ON_BLUE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::ON_CYAN = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::ON_GREEN = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::ON_MAGENTA = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::ON_RED = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::ON_WHITE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::ON_YELLOW = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::OVERLINE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::OVERLINE_OFF = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::POSITIVE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::RAPID = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::RAPID_BLINK = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::RED = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::RESET = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:20
ANSI::Constants::RESTORE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::REVEAL = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::REVERSE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:20
ANSI::Constants::SAVE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::SHOW = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::SLOW_BLINK = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::STRIKE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::SWAP = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::UNDERLINE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::UNDERLINE_OFF = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::UNDERSCORE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::WHITE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/constants.rb:16
ANSI::Constants::YELLOW = T.let(T.unsafe(nil), String)

# Diff produces colorized differences of two string or objects.
#
# pkg:gem/ansi#lib/ansi/diff.rb:7
class ANSI::Diff
  # Setup new Diff object. If the objects given are not Strings
  # and do not have `#to_str` defined to coerce them to such, then
  # their `#inspect` methods are used to convert them to strings
  # for comparison.
  #
  # @param [Object] object1
  #   First object to compare.
  #
  # @param [Object] object2
  #   Second object to compare.
  #
  # @param [Hash] options
  #   Options for contoller the way difference is shown. (Not yet used.)
  #
  # pkg:gem/ansi#lib/ansi/diff.rb:33
  def initialize(object1, object2, options = T.unsafe(nil)); end

  # Returns the first object's difference string.
  #
  # pkg:gem/ansi#lib/ansi/diff.rb:41
  def diff1; end

  # Returns the second object's difference string.
  #
  # pkg:gem/ansi#lib/ansi/diff.rb:46
  def diff2; end

  # Returns both first and second difference strings separated by a
  # the given `separator`. The default is `$/`, the record separator.
  #
  # @param [String] separator
  #   The string to use as the separtor between the difference strings.
  #
  # @return [String] Joined difference strings.
  #
  # pkg:gem/ansi#lib/ansi/diff.rb:67
  def join(separator = T.unsafe(nil)); end

  # Returns the first and second difference strings in an array.
  #
  # @return [Array] Both difference strings.
  #
  # pkg:gem/ansi#lib/ansi/diff.rb:74
  def to_a; end

  # Returns both first and second difference strings separated by a
  # new line character.
  #
  # @todo Should we use `$/` record separator instead?
  #
  # @return [String] Joined difference strings.
  #
  # pkg:gem/ansi#lib/ansi/diff.rb:56
  def to_s; end

  private

  # Oh, I should have documented this will I knew what the
  # hell it was doing ;)
  #
  # pkg:gem/ansi#lib/ansi/diff.rb:139
  def common(x, y); end

  # Take two plain strings and produce colorized
  # versions of each highlighting their differences.
  #
  # @param [String] x
  #   First string to compare.
  #
  # @param [String] y
  #   Second string to compare.
  #
  # @return [Array<String>] The two difference strings.
  #
  # pkg:gem/ansi#lib/ansi/diff.rb:120
  def compare(x, y); end

  # Ensure the object of comparison is a string. If +object+ is not
  # an instance of String then it wll be converted to one by calling
  # either #to_str, if the object responds to it, or #inspect.
  #
  # pkg:gem/ansi#lib/ansi/diff.rb:97
  def convert(object); end

  # Take two plain strings and produce colorized
  # versions of each highlighting their differences.
  #
  # @param [String] string1
  #   First string to compare.
  #
  # @param [String] string2
  #   Second string to compare.
  #
  # @return [Array<String>] The two difference strings.
  #
  # pkg:gem/ansi#lib/ansi/diff.rb:90
  def diff_string(string1, string2); end

  # Least common string.
  #
  # pkg:gem/ansi#lib/ansi/diff.rb:168
  def lcs(s1, s2); end

  # Hmm... is this even useful?
  #
  # pkg:gem/ansi#lib/ansi/diff.rb:197
  def lcs_size(s1, s2); end

  class << self
    # Highlights the differnce between two strings.
    #
    # This class method is equivalent to calling:
    #
    #   ANSI::Diff.new(object1, object2).to_a
    #
    # pkg:gem/ansi#lib/ansi/diff.rb:15
    def diff(object1, object2, options = T.unsafe(nil)); end
  end
end

# Rotation of colors for diff output.
#
# pkg:gem/ansi#lib/ansi/diff.rb:108
ANSI::Diff::COLORS = T.let(T.unsafe(nil), Array)

# = ANSI::Logger
#
# Extended variation of Ruby's standard Logger library that supports
# color output.
#
#   log = ANSI::Logger.new
#
#   log.formatter do |severity, timestamp, progname, msg|
#     ANSI::Logger::SIMPLE_FORMAT % [severity, msg]
#   end
#
# --
# TODO: What's all this about then?
#
# When using debug level logger messages always append 'if $DBG'
# at the end. This hack is needed because Ruby does not support
# lazy evaluation (lisp macros).
# ++
#
# pkg:gem/ansi#lib/ansi/logger.rb:27
class ANSI::Logger < ::Logger
  # pkg:gem/ansi#lib/ansi/logger.rb:50
  def ansicolor=(on); end

  # pkg:gem/ansi#lib/ansi/logger.rb:45
  def ansicolor?; end

  # pkg:gem/ansi#lib/ansi/logger.rb:97
  def debug(progname = T.unsafe(nil), &block); end

  # pkg:gem/ansi#lib/ansi/logger.rb:103
  def error(progname = T.unsafe(nil), &block); end

  # pkg:gem/ansi#lib/ansi/logger.rb:109
  def fatal(progname = T.unsafe(nil), &block); end

  # Dictate the way in which this logger should format the
  # messages it displays. This method requires a block. The
  # block should return formatted strings given severity,
  # timestamp, progname and msg.
  #
  # === Example
  #
  #   logger = ANSI::Logger.new
  #
  #   logger.formatter do |severity, timestamp, progname, msg|
  #     "#{progname}@#{timestamp} - #{severity}::#{msg}"
  #   end
  #
  # pkg:gem/ansi#lib/ansi/logger.rb:67
  def formatter(&block); end

  # pkg:gem/ansi#lib/ansi/logger.rb:85
  def info(progname = T.unsafe(nil), &block); end

  # pkg:gem/ansi#lib/ansi/logger.rb:72
  def styles(options = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/logger.rb:91
  def warn(progname = T.unsafe(nil), &block); end

  private

  # pkg:gem/ansi#lib/ansi/logger.rb:134
  def debug_with_color; end

  # pkg:gem/ansi#lib/ansi/logger.rb:128
  def error_with_color; end

  # pkg:gem/ansi#lib/ansi/logger.rb:140
  def fatal_with_color; end

  # pkg:gem/ansi#lib/ansi/logger.rb:116
  def info_with_color; end

  # pkg:gem/ansi#lib/ansi/logger.rb:122
  def warn_with_color; end
end

# pkg:gem/ansi#lib/ansi/logger.rb:31
ANSI::Logger::DETAILED_FORMAT = T.let(T.unsafe(nil), String)

# Some available logging formats.
#
# pkg:gem/ansi#lib/ansi/logger.rb:30
ANSI::Logger::SIMPLE_FORMAT = T.let(T.unsafe(nil), String)

# This module is designed specifically for mixing into
# String-like classes or extending String-like objects.
#
# Generally speaking the String#ansi method is the more
# elegant approach to modifying a string with codes
# via a method call. But in some cases this Mixin's design
# might be preferable. Indeed, it original intent was
# as a compatability layer for the +colored+ gem.
#
# pkg:gem/ansi#lib/ansi/mixin.rb:13
module ANSI::Mixin
  # pkg:gem/ansi#lib/ansi/mixin.rb:27
  def black; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:48
  def black_on_blue; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:50
  def black_on_cyan; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:46
  def black_on_green; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:49
  def black_on_magenta; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:45
  def black_on_red; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:51
  def black_on_white; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:47
  def black_on_yellow; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:20
  def blink; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:31
  def blue; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:77
  def blue_on_black; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:82
  def blue_on_cyan; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:79
  def blue_on_green; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:81
  def blue_on_magenta; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:78
  def blue_on_red; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:83
  def blue_on_white; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:80
  def blue_on_yellow; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:15
  def bold; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:24
  def concealed; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:33
  def cyan; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:93
  def cyan_on_black; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:97
  def cyan_on_blue; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:95
  def cyan_on_green; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:98
  def cyan_on_magenta; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:94
  def cyan_on_red; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:99
  def cyan_on_white; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:96
  def cyan_on_yellow; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:16
  def dark; end

  # Move cursor to line and column, insert +self.to_s+ and return to
  # original positon.
  #
  # pkg:gem/ansi#lib/ansi/mixin.rb:111
  def display(line, column = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/mixin.rb:29
  def green; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:61
  def green_on_black; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:64
  def green_on_blue; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:66
  def green_on_cyan; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:65
  def green_on_magenta; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:62
  def green_on_red; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:67
  def green_on_white; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:63
  def green_on_yellow; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:17
  def italic; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:32
  def magenta; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:85
  def magenta_on_black; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:89
  def magenta_on_blue; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:90
  def magenta_on_cyan; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:87
  def magenta_on_green; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:86
  def magenta_on_red; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:91
  def magenta_on_white; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:88
  def magenta_on_yellow; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:23
  def negative; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:36
  def on_black; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:40
  def on_blue; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:42
  def on_cyan; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:38
  def on_green; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:41
  def on_magenta; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:37
  def on_red; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:43
  def on_white; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:39
  def on_yellow; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:21
  def rapid; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:28
  def red; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:53
  def red_on_black; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:56
  def red_on_blue; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:58
  def red_on_cyan; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:54
  def red_on_green; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:57
  def red_on_magenta; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:59
  def red_on_white; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:55
  def red_on_yellow; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:22
  def reverse; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:25
  def strike; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:18
  def underline; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:19
  def underscore; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:34
  def white; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:101
  def white_on_black; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:105
  def white_on_blue; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:107
  def white_on_cyan; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:103
  def white_on_green; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:106
  def white_on_magenta; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:102
  def white_on_red; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:104
  def white_on_yellow; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:30
  def yellow; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:69
  def yellow_on_black; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:72
  def yellow_on_blue; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:74
  def yellow_on_cyan; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:71
  def yellow_on_green; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:73
  def yellow_on_magenta; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:70
  def yellow_on_red; end

  # pkg:gem/ansi#lib/ansi/mixin.rb:75
  def yellow_on_white; end
end

# = Progressbar
#
# Progressbar is a text-based progressbar library.
#
#   pbar = Progressbar.new( "Demo", 100 )
#   100.times { pbar.inc }
#   pbar.finish
#
# pkg:gem/ansi#lib/ansi/progressbar.rb:20
class ANSI::ProgressBar
  # pkg:gem/ansi#lib/ansi/progressbar.rb:22
  def initialize(title, total, out = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:54
  def bar_mark=(mark); end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:57
  def barmark=(mark); end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:138
  def clear; end

  # For backward compatability
  #
  # pkg:gem/ansi#lib/ansi/progressbar.rb:91
  def file_transfer_mode; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:93
  def finish; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:99
  def flush; end

  # Set format and format arguments.
  #
  # pkg:gem/ansi#lib/ansi/progressbar.rb:45
  def format(format, *arguments); end

  # Set format and format arguments.
  #
  # pkg:gem/ansi#lib/ansi/progressbar.rb:45
  def format=(_arg0); end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:46
  def format_arguments; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:46
  def format_arguments=(_arg0); end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:103
  def halt; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:130
  def inc(step = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:142
  def inspect; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:58
  def mark=(mark); end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:124
  def reset; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:108
  def set(count); end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:79
  def standard_mode; end

  # Set ANSI styling options.
  #
  # pkg:gem/ansi#lib/ansi/progressbar.rb:74
  def style(options); end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:47
  def styles; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:47
  def styles=(_arg0); end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:50
  def title=(str); end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:60
  def total_overflow=(boolv); end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:85
  def transfer_mode; end

  private

  # pkg:gem/ansi#lib/ansi/progressbar.rb:210
  def bar; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:166
  def bytes; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:280
  def colorize(part, style); end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:149
  def convert_bytes(bytes); end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:189
  def elapsed; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:206
  def eol; end

  # ETA stands for Estimated Time of Arrival.
  #
  # pkg:gem/ansi#lib/ansi/progressbar.rb:179
  def eta; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:170
  def format_time(t); end

  # TODO: Use Terminal.terminal_width instead.
  #
  # pkg:gem/ansi#lib/ansi/progressbar.rb:228
  def get_width; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:215
  def percentage; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:247
  def show; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:266
  def show_progress; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:194
  def stat; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:198
  def stat_for_file_transfer; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:223
  def title; end

  # pkg:gem/ansi#lib/ansi/progressbar.rb:161
  def transfer_rate; end
end

# pkg:gem/ansi#lib/ansi/progressbar.rb:289
ANSI::Progressbar = ANSI::ProgressBar

# pkg:gem/ansi#lib/ansi/chart.rb:86
ANSI::SPECIAL_CHART = T.let(T.unsafe(nil), Hash)

# IMPORTANT! ANSI::String is experimental!!!
#
# ANSI::String stores a regular string (`@text`) and an associative
# array that ties a character index to an ANSI code (`marks`).
# For example is we have the string:
#
#   "Big Apple"
#
# And applied the color red to it, the marks list would be:
#
#   [[0, :red], [9, :clear]]
#
# TODO: In the future we may be able to subclass String,
# instead of delegating via @text, but not until it is more
# compatible.
#
# pkg:gem/ansi#lib/ansi/string.rb:25
class ANSI::String
  # New Ansi::String
  #
  # pkg:gem/ansi#lib/ansi/string.rb:33
  def initialize(text = T.unsafe(nil), marks = T.unsafe(nil)); end

  # Add one String to another, or to a regular String.
  #
  # pkg:gem/ansi#lib/ansi/string.rb:73
  def +(other); end

  # pkg:gem/ansi#lib/ansi/string.rb:132
  def [](*args); end

  # pkg:gem/ansi#lib/ansi/string.rb:194
  def ansi(code); end

  # pkg:gem/ansi#lib/ansi/string.rb:204
  def ansi!(code); end

  # pkg:gem/ansi#lib/ansi/string.rb:214
  def black; end

  # pkg:gem/ansi#lib/ansi/string.rb:225
  def black!; end

  # pkg:gem/ansi#lib/ansi/string.rb:213
  def blue; end

  # pkg:gem/ansi#lib/ansi/string.rb:224
  def blue!; end

  # pkg:gem/ansi#lib/ansi/string.rb:219
  def bold; end

  # pkg:gem/ansi#lib/ansi/string.rb:230
  def bold!; end

  # pkg:gem/ansi#lib/ansi/string.rb:201
  def color(code); end

  # pkg:gem/ansi#lib/ansi/string.rb:209
  def color!(code); end

  # pkg:gem/ansi#lib/ansi/string.rb:217
  def cyan; end

  # pkg:gem/ansi#lib/ansi/string.rb:228
  def cyan!; end

  # Downcase the string.
  #
  # pkg:gem/ansi#lib/ansi/string.rb:69
  def downcase; end

  # pkg:gem/ansi#lib/ansi/string.rb:70
  def downcase!; end

  # pkg:gem/ansi#lib/ansi/string.rb:212
  def green; end

  # pkg:gem/ansi#lib/ansi/string.rb:223
  def green!; end

  # See #gsub!.
  #
  # pkg:gem/ansi#lib/ansi/string.rb:189
  def gsub(pattern, replacement = T.unsafe(nil), &block); end

  # pkg:gem/ansi#lib/ansi/string.rb:163
  def gsub!(pattern, replacement = T.unsafe(nil), &block); end

  # pkg:gem/ansi#lib/ansi/string.rb:215
  def magenta; end

  # pkg:gem/ansi#lib/ansi/string.rb:226
  def magenta!; end

  # pkg:gem/ansi#lib/ansi/string.rb:30
  def marks; end

  # pkg:gem/ansi#lib/ansi/string.rb:211
  def red; end

  # pkg:gem/ansi#lib/ansi/string.rb:222
  def red!; end

  # The size of the base text.
  #
  # pkg:gem/ansi#lib/ansi/string.rb:62
  def size; end

  # slice
  #
  # pkg:gem/ansi#lib/ansi/string.rb:98
  def slice(*args); end

  # See #sub!.
  #
  # pkg:gem/ansi#lib/ansi/string.rb:158
  def sub(pattern, replacement = T.unsafe(nil), &block); end

  # This is more limited than the normal String method.
  # It does not yet support a block, and +replacement+
  # won't substitue for \1, \2, etc.
  #
  # TODO: block support.
  #
  # pkg:gem/ansi#lib/ansi/string.rb:139
  def sub!(pattern, replacement = T.unsafe(nil), &block); end

  # pkg:gem/ansi#lib/ansi/string.rb:29
  def text; end

  # Convert Ansi::String object to normal String.
  # This converts the intental markup codes to ANSI codes.
  #
  # pkg:gem/ansi#lib/ansi/string.rb:41
  def to_s; end

  # ANSI::String is a type of String.
  #
  # pkg:gem/ansi#lib/ansi/string.rb:59
  def to_str; end

  # pkg:gem/ansi#lib/ansi/string.rb:220
  def underline; end

  # pkg:gem/ansi#lib/ansi/string.rb:231
  def underline!; end

  # Upcase the string.
  #
  # pkg:gem/ansi#lib/ansi/string.rb:65
  def upcase; end

  # pkg:gem/ansi#lib/ansi/string.rb:66
  def upcase!; end

  # pkg:gem/ansi#lib/ansi/string.rb:216
  def yellow; end

  # pkg:gem/ansi#lib/ansi/string.rb:227
  def yellow!; end

  private

  # pkg:gem/ansi#lib/ansi/string.rb:236
  def shift_marks(index, delta, marks = T.unsafe(nil)); end

  # pkg:gem/ansi#lib/ansi/string.rb:250
  def shift_marks!(index, delta); end
end

# pkg:gem/ansi#lib/ansi/string.rb:27
ANSI::String::CLR = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/table.rb:6
class ANSI::Table
  # The Table class can be used to output nicely formatted
  # tables with division lines and alignment.
  #
  # table - array of array
  #
  # options[:align]   - align :left or :right
  # options[:padding] - space to add to each cell
  # options[:fit]     - fit to screen width
  # options[:border]  -
  #
  # The +format+ block must return ANSI codes to apply
  # to each cell.
  #
  # Other Implementations:
  #
  # * http://github.com/visionmedia/terminal-table
  # * http://github.com/aptinio/text-table
  #
  # TODO: Support for table headers and footers.
  #
  # pkg:gem/ansi#lib/ansi/table.rb:27
  def initialize(table, options = T.unsafe(nil), &format); end

  # pkg:gem/ansi#lib/ansi/table.rb:49
  def align; end

  # pkg:gem/ansi#lib/ansi/table.rb:49
  def align=(_arg0); end

  # pkg:gem/ansi#lib/ansi/table.rb:55
  def border; end

  # pkg:gem/ansi#lib/ansi/table.rb:55
  def border=(_arg0); end

  # Fit to scree width.
  #
  # pkg:gem/ansi#lib/ansi/table.rb:43
  def fit; end

  # Fit to scree width.
  #
  # pkg:gem/ansi#lib/ansi/table.rb:43
  def fit=(_arg0); end

  # pkg:gem/ansi#lib/ansi/table.rb:52
  def format; end

  # pkg:gem/ansi#lib/ansi/table.rb:52
  def format=(_arg0); end

  # pkg:gem/ansi#lib/ansi/table.rb:46
  def padding; end

  # pkg:gem/ansi#lib/ansi/table.rb:46
  def padding=(_arg0); end

  # pkg:gem/ansi#lib/ansi/table.rb:40
  def table; end

  # pkg:gem/ansi#lib/ansi/table.rb:40
  def table=(_arg0); end

  # pkg:gem/ansi#lib/ansi/table.rb:58
  def to_s; end

  private

  # pkg:gem/ansi#lib/ansi/table.rb:158
  def ansi_formating(cell, col, row); end

  # pkg:gem/ansi#lib/ansi/table.rb:149
  def apply_format(str, cell, col, row); end

  # pkg:gem/ansi#lib/ansi/table.rb:123
  def cell_template(max); end

  # Number of columns based on the first row of table.
  #
  # @return [Integer] number of columns
  #
  # pkg:gem/ansi#lib/ansi/table.rb:118
  def column_size; end

  # TODO: make more efficient
  #
  # pkg:gem/ansi#lib/ansi/table.rb:133
  def dividing_line; end

  # TODO: look at the lines and figure out how many columns will fit
  #
  # pkg:gem/ansi#lib/ansi/table.rb:91
  def fit_width; end

  # Calculate the maximun column sizes.
  #
  # @return [Array] maximum size for each column
  #
  # pkg:gem/ansi#lib/ansi/table.rb:99
  def max_columns(fit = T.unsafe(nil)); end
end

# = Terminal
#
# This library is based of HighLine's SystemExtensions
# by James Edward Gray II.
#
# Copyright 2006 Gray Productions
#
# Distributed under the tems of the
# {Ruby software license}[http://www.ruby-lang.org/en/LICENSE.txt].
#
# pkg:gem/ansi#lib/ansi/terminal.rb:13
module ANSI::Terminal
  private

  # Unix savvy getc().  (First choice.)
  #
  # *WARNING*:  This method requires the "termios" library!
  #
  #
  # Windows savvy getc().
  #
  #
  #
  # Curses savvy getc().
  #
  #
  # Unix savvy getc().  (second choice)
  #
  # *WARNING*:  This method requires the external "stty" program!
  #
  # pkg:gem/ansi#lib/ansi/terminal/stty.rb:16
  def get_character(input = T.unsafe(nil)); end

  # Switched the input mode to raw and disables echo.
  #
  # *WARNING*:  This method requires the external "stty" program!
  #
  # pkg:gem/ansi#lib/ansi/terminal/stty.rb:31
  def raw_no_echo_mode; end

  # Restores a previously saved input mode.
  #
  # *WARNING*:  This method requires the external "stty" program!
  #
  # pkg:gem/ansi#lib/ansi/terminal/stty.rb:41
  def restore_mode; end

  # Get the height of the terminal window.
  #
  # pkg:gem/ansi#lib/ansi/terminal.rb:37
  def terminal_height; end

  # A Unix savvy method to fetch the console columns, and rows.
  # A Windows savvy method to fetch the console columns, and rows.
  # A Unix savvy method to fetch the console columns, and rows.
  #
  # pkg:gem/ansi#lib/ansi/terminal/stty.rb:46
  def terminal_size; end

  # Get the width of the terminal window.
  #
  # pkg:gem/ansi#lib/ansi/terminal.rb:32
  def terminal_width; end

  class << self
    # Unix savvy getc().  (First choice.)
    #
    # *WARNING*:  This method requires the "termios" library!
    #
    #
    # Windows savvy getc().
    #
    #
    #
    # Curses savvy getc().
    #
    #
    # Unix savvy getc().  (second choice)
    #
    # *WARNING*:  This method requires the external "stty" program!
    #
    # pkg:gem/ansi#lib/ansi/terminal/stty.rb:16
    def get_character(input = T.unsafe(nil)); end

    # Switched the input mode to raw and disables echo.
    #
    # *WARNING*:  This method requires the external "stty" program!
    #
    # pkg:gem/ansi#lib/ansi/terminal/stty.rb:31
    def raw_no_echo_mode; end

    # Restores a previously saved input mode.
    #
    # *WARNING*:  This method requires the external "stty" program!
    #
    # pkg:gem/ansi#lib/ansi/terminal/stty.rb:41
    def restore_mode; end

    # Get the height of the terminal window.
    #
    # pkg:gem/ansi#lib/ansi/terminal.rb:37
    def terminal_height; end

    # A Unix savvy method to fetch the console columns, and rows.
    # A Windows savvy method to fetch the console columns, and rows.
    # A Unix savvy method to fetch the console columns, and rows.
    #
    # pkg:gem/ansi#lib/ansi/terminal/stty.rb:46
    def terminal_size; end

    # Get the width of the terminal window.
    #
    # pkg:gem/ansi#lib/ansi/terminal.rb:32
    def terminal_width; end
  end
end

# pkg:gem/ansi#lib/ansi/terminal.rb:26
ANSI::Terminal::CHARACTER_MODE = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/version.rb:2
ANSI::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/ansi#lib/ansi/logger.rb:35
class Logger::LogDevice
  # pkg:gem/ansi#lib/ansi/logger.rb:36
  def ansicolor=(_arg0); end

  # pkg:gem/ansi#lib/ansi/logger.rb:38
  def ansicolor?; end
end

class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin

  private

  # Kernel method
  #
  # pkg:gem/ansi#lib/ansi.rb:19
  def ansi(string, *codes); end
end

# pkg:gem/ansi#lib/ansi/core.rb:4
class String
  include ::Comparable

  # pkg:gem/ansi#lib/ansi/core.rb:7
  def ansi(*codes); end

  # pkg:gem/ansi#lib/ansi/core.rb:16
  def ansi!(*codes); end

  # pkg:gem/ansi#lib/ansi/core.rb:21
  def unansi; end

  # pkg:gem/ansi#lib/ansi/core.rb:26
  def unansi!; end
end
