# This file strictly follows the rules defined in the Ruby style guide:
#   http://shopify.github.io/ruby-style-guide/
inherit_gem:
  rubocop-shopify: rubocop.yml

require:
 - rubocop-sorbet

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
  - 'rbi/**/*'
  - 'vendor/**/*'

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['\A\s*#:']

Sorbet:
  Enabled: true

Sorbet/TrueSigil:
  Enabled: true
