name: rbi

type: ruby

up:
  - ruby: 2.7.2
  - bundler

commands:
  console:
    desc:   'start a console'
    run:    bin/console
  run:
    desc:   'start the application'
    run:    bin/run
  test:
    syntax:
      argument: file
      optional: args...
    run: bin/test
  typecheck:
    desc: 'run Sorbet typechecking'
    aliases: ['tc']
    depends-railgun: false
    run: bundle exec srb tc
  rbi:
    desc:   "generate Ruby interface files for Sorbet"
    subcommands:
      gems:
        desc: "updates gem RBI files. Use 'dev rbi gems <gem, ...>' to update individual gem RBI files."
        run: bundle exec tapioca sync -c 'dev rbi gems'
