name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ "3.3", "3.4", "4.0" ]
    name: Test Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up Ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run type check
        run: bin/typecheck

      - name: Lint Ruby files
        run: bin/style --config .rubocop.yml

      - name: Run tests
        run: bin/test

      - name: Check exported RBI files
        run: bin/export-rbi --check-sync

      - name: Check shims
        run: bin/tapioca check-shims
